# Docker Compose for OneDrive Telegram Bot
version: '3.8'

services:
  onedrive-bot:
    build: .
    container_name: onedrive-telegram-bot
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Optional: Mount volume for persistent data
    volumes:
      - ./data:/app/data
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Optional: Create a network for multiple services
networks:
  default:
    name: telegram-bots
