name: Scheduled Bot Runner

on:
  schedule:
    # Run every day at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
    # Run every day at 6 PM UTC
    - cron: '0 18 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      schedule_duration:
        description: 'Duration for scheduled run (minutes)'
        required: false
        default: '120'
        type: string

jobs:
  scheduled-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 150  # 2.5 hours maximum
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create environment file
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
        echo "TENANT_ID=${{ secrets.TENANT_ID }}" >> .env
        echo "USER_ID=${{ secrets.USER_ID }}" >> .env
        echo "ADMIN_USER_ID=${{ secrets.ADMIN_USER_ID }}" >> .env

    - name: Update index if needed
      run: |
        echo "Checking if index needs update..."
        python indexer.py --stats

    - name: Run scheduled bot session
      timeout-minutes: ${{ fromJSON(github.event.inputs.schedule_duration || '120') }}
      env:
        BOT_RUNTIME_MINUTES: ${{ github.event.inputs.schedule_duration || '120' }}
      run: |
        echo "Starting scheduled bot session..."
        python github_runner.py

    - name: Cleanup
      if: always()
      run: |
        rm -f .env
        echo "Scheduled run completed"
